name: gds
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.8    # Python version 3.8
    - geopandas     # Geospatial extension of pandas
    - matplotlib    # 2D plotting library
    - numpy         # N-d array and numerics 
    - pandas        # Labeled data analysis
    - jupyter       # Interactive notebooks
    - cenpy         # Access to Census data
    - shapely       # Vector operations
    - jupyterlab    # Web-based IDE for Project Jupyter
    - osmnx         # OpenStreetMap
    - networkx      # Network analysis
    - rioxarray     # Read/write gridded data
    - scikit-learn  # Machine learning
    - selenium      # Automated web browsers
    - bs4           # Web scraping
    - jupyter-book  # Produce book
    - black	    # Style configuration
    - descartes     # Geometric objects as matplotlib paths and patches
    - momepy        # Urban morphology measuring toolkit
